name: Auto Merge Main to Testing

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
      - name: Configure Git
        run: |
          git config --global user.name 'iamsriramm'
          git config --global user.email 'sriramsmart789@gmail.com'
      - name: Fetch all branches
        run: git fetch --all
      - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrelated-histories
      - name: Push changes
        run: git push origin testing